version: '3'
services:
  app:
    container_name: alphaherd_webapp
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3025:3000'
    env_file:
      - .env