version: '3'
services:
  app:
    container_name: alphaherd_webapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3025:3000'
    env_file:
      - .env