version: '3'
services:
  app:
    container_name: alphaherd_webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3025:3000'
    env_file:
      - .env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'